### ISSUE TITLE
SalesforceIdFormatter.to_15 isn't converting correctly

### ISSUE THREAD

**Issue by nstuart-at-salesforce** [heroku/salesforce_id_formatter#6]
See [this post](https://salesforce.stackexchange.com/questions/1653/what-are-salesforce-ids-composed-of/1663) on how conversion is done. 

When converting from 18-char to 15-char ID's, use the last 3 chars to determine where case change needs to happen in the first 15 characters.

**Comment by nstuart-at-salesforce** [comment]
@raul Sorry to bother you, but are you still the maintainer of this library? What's the process for having a PR approved and merged?

I discovered that it contains a bug in the to_15 implementation that could lead to id collisions. I created a PR to fix this and added some unit tests.

**Comment by raul** [comment]
No bothering at all @nstuart-at-salesforce, we're in fact super grateful for your work not only catching that bug but also sending a fix with a neat test coverage! 🙌  I'm adding this PR to our team's backlog, we're expecting to review it and release a new version during the next few days.

**Comment by mrigdon-zz** [comment]
Hi @raul , just checking up on the status of this one. Thanks for looking into it.

**Comment by raul** [comment]
Hi folks! Sorry, our team is focused on some special activities this week but we'll get back to our regular backlog (which includes reviewing and merging this PR) next week.

**Comment by raul** [comment]
Apologies for the delay folks 🙏  and thank you again for the fix! 🙌 !

**Comment by raul** [comment]
The new v1.2.0 includes your fix, thank you! ❤️
